name: Deploy to Heroku
on:
  push:
    branches: [release]

jobs:
  deploy_to_heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout src
        uses: actions/checkout@v2
      - name: Echo branch
        run: echo "Branch ${{ github.ref_name }}"
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: lyon-pokemart
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          branch: ${{ github.ref_name }}
          